export type Lang = "nl" | "en";
export const copy = {
nl: {
pageTitle:"Pauline kookt | Borrelboxen, lunch & buffetten in Arcen",meta:"Persoonlijke catering vanuit Arcen. Borrelboxen, lunch, brunch en warme of koude buffetten voor jouw feest of bedrijf. Een voorstel op maat, antwoord binnen 48 uur.",skip:"Naar het aanbod",navigation:"Hoofdnavigatie",closeMenu:"Menu sluiten",openMenu:"Menu openen",close:"Sluiten",
nav:{services:[["box","Grazing box"],["lunch","Lunch of brunch"],["cold","Warm & koud buffet"]],story:"Over Pauline",contact:"Contact"},
hero:{eyebrow:"CATERING · ARCEN & OMGEVING",line1:"Lekker eten.",line2:"Fijn samen.",intro:"Van een goedgevulde borrelbox tot een tafel voor je hele gezelschap. Persoonlijk bereid, met aandacht voor jouw moment.",cta:"Ontdek het aanbod",secondary:"Vertel me je plannen",note:"Met liefde, van Pauline",bottom:"VOOR KLEINE FEESTJES & GROTE MOMENTEN"},
offers:{eyebrow:"3 MANIEREN OM SAMEN TE GENIETEN",title1:"Jouw gezelschap.",title2:"Jouw tafel.",intro:"Een babyshower thuis, een verjaardag of een lunch met het team. Kies wat bij je past; de rest stemmen we samen af.",details:"Dit kun je verwachten",personal:"Iedere tafel is anders.",flexible:"Een eigen idee, favoriete gerecht of vegetarische wens? Vertel het me gerust.",ask:"Bespreek je wensen",cards:[
{id:"box",tag:"BORRELEN & DELEN",title:"Grazing box",alt:"Kazen, brood, noten en groente op een rijkgevulde borrelplank",description:"Een goedgevulde borrelbox met kaas, charcuterie, dips, brood en verse extra’s. Klaar om op tafel te zetten.",expectation:"Voor een borrel, verjaardag of avond met vrienden."},
{id:"lunch",tag:"ZOET & HARTIG",title:"Lunch of brunch",alt:"Brood met gerookte zalm, roomkaas, komkommer en kruiden",description:"Belegde broodjes, frisse salades en iets zoets. Of maak er een brunch van met croissants, yoghurt en fruit.",expectation:"Voor een babyshower, familietafel of teamlunch."},
{id:"cold",tag:"KOUD, WARM OF ALLEBEI",title:"Een buffet op maat",alt:"Een buffet met belegde broodjes en verschillende hapjes",description:"Kleurrijke schalen om te delen, warme gerechten of een combinatie. We stellen één passend menu samen voor jouw gezelschap.",expectation:"Voor een feest thuis of een bijeenkomst op het werk."}]},
occasionsLabel:"Gelegenheden",occasions:["Babyshowers","Verjaardagen","Jubilea","Teamlunches","Bedrijfsborrels"],
menu:{eyebrow:"WAT KOMT ER OP TAFEL?",title1:"Laat je",title2:"lekker inspireren.",intro:"Een voorproefje van de mogelijkheden. Vertel me wat je aanspreekt; ik denk graag mee over een menu dat klopt.",choose:"Kies een type menu",instruction:"Kies hieronder een aanbod en bekijk het bijbehorende menu.",view:"Bekijk menu",current:"Menu geopend",tabs:[["box","Grazing box"],["lunch","Lunch & brunch"],["cold","Koud buffet"],["warm","Warm buffet"]],expect:"GOED OM TE WETEN",cta:"Dit past bij mijn plannen",inspiration:"MENU-INSPIRATIE",footnote:"Dit zijn menu-ideeën. Samen bevestigen we de gerechten, hoeveelheden en prijs. Geef allergieën en dieetwensen vooraf door."},
story:{eyebrow:"NIEUW IN ARCEN · SINDS 2026",title1:"Aangenaam,",title2:"ik ben Pauline.",alt:"Pauline, de persoon achter Pauline kookt",caption:"Het gezicht achter jouw tafel",p1:"Bij ons thuis begon samenzijn vaak in de keuken. Mijn ouders en oma kookten om de familie bij elkaar te brengen. Dat gevoel neem ik mee in alles wat ik maak.",p2:"Ik ben opgegroeid in de Provence, ben moeder van twee kinderen en start nu mijn eigen catering in Arcen. Pauline kookt is nieuw. Mijn plezier in koken en delen is dat al veel langer.",p3:"Ik luister naar jouw wensen, bereid met zorg en geef elk moment mijn volle aandacht. Lekker eten, een mooie presentatie en een gastvrij gevoel: daar doe ik het voor."},
process:{eyebrow:"VAN IDEE NAAR EEN FIJNE TAFEL",title:"Zo regelen we het.",cta:"Laten we beginnen",steps:[{title:"Vertel me je plannen",body:"Een datum, ongeveer hoeveel gasten en jouw idee. Nog niet alles duidelijk? Dat is helemaal prima."},{title:"Een voorstel voor jou",body:"Ik reageer binnen 48 uur. We bespreken het menu, de mogelijkheden en de bezorging, met een heldere prijs vooraf."},{title:"Jij bent erbij",body:"Na jouw akkoord spreken we alles af. Ik zorg voor het eten, zodat jij tijd hebt voor je gasten."}]},
contact:{eyebrow:"KLEIN IDEE OF AL CONCRETE PLANNEN",title1:"Laten we iets",title2:"lekkers plannen.",intro:"Vertel me wat je voor ogen hebt. Ik denk graag met je mee, ook als je nog niet precies weet wat je zoekt.",response:"Persoonlijk antwoord binnen 48 uur",deliveryTitle:"Vanuit Arcen, naar jouw moment.",delivery:"Ik bezorg zelf in Arcen en omgeving. Ook vlak over de Duitse grens zijn aanvragen welkom. Geef je plaats of postcode door; afstand, bezorgkosten en eventuele opbouw staan vooraf in je voorstel."},
serviceOptions:[["unsure","Ik weet het nog niet"],["box","Grazing box"],["lunch","Lunch of brunch"],["buffet","Koud of warm buffet"],["other","Een ander idee / een combinatie"]],
form:{heading:"Waar denk je aan?",description:"Alleen je naam en e-mail zijn nodig. Vul de rest in voor zover je het al weet.",name:"Naam",email:"E-mail",service:"Ik ben geïnteresseerd in",date:"Datum",dateOptional:"Datum (als bekend)",guests:"Aantal gasten",guestsOptional:"Gasten (ongeveer)",guestsPlaceholder:"Bijv. 20",occasion:"Gelegenheid",occasionOptional:"Gelegenheid (optioneel)",occasionPlaceholder:"Bijv. verjaardag of teamlunch",city:"Plaats / postcode",cityOptional:"Plaats / postcode (optioneel)",cityPlaceholder:"Bijv. Arcen of Straelen",wishes:"Wensen",wishesOptional:"Vertel me je wensen (optioneel)",wishesPlaceholder:"Wat vier je? Favoriete gerechten, een budget of dieetwensen?",emailButton:"Verder via e-mail",handoff:"Je e-mailapp of WhatsApp opent met je aanvraag ingevuld. Controleer het bericht en verstuur het daar zelf.",copy:"Kopieer mijn aanvraag",privacy:"Privacy",unknown:"Nog niet bekend",noWishes:"Bespreek ik graag samen.",greeting:"Hallo Pauline,",intro:"Ik wil graag de mogelijkheden bespreken voor mijn bijeenkomst.",signoff:"Hartelijke groet,",subject:"Cateringaanvraag — Pauline kookt",draftNotice:"Je bericht staat klaar om te versturen. Rond het versturen af in je e-mailapp of WhatsApp. Er is nog niets automatisch verzonden.",copied:"Je aanvraag is gekopieerd. Plak hem in een e-mail aan paulinecooks@gmail.com of in WhatsApp en verstuur hem daar.",copyFailed:"Kopiëren lukte niet. Gebruik de e-mail- of WhatsApp-knop, of mail rechtstreeks naar paulinecooks@gmail.com."},
privacy:{intro:"Je aanvraag, persoonlijk behandeld.",paragraphs:["Wat je hier invult, wordt pas gedeeld wanneer je zelf het bericht verstuurt in je e-mailapp of WhatsApp. Deze pagina slaat je formuliergegevens niet op.","Pauline gebruikt de gegevens die je toestuurt om je vraag te beantwoorden en een eventuele cateringopdracht af te spreken. Vragen over je gegevens? Mail Pauline rechtstreeks.","De website onthoudt alleen je taalkeuze op dit apparaat. Er zijn geen advertentietrackers toegevoegd. Voor het gebruik van e-mail en WhatsApp gelden ook de voorwaarden van die diensten."]},
gallery:{eyebrow:"OP TAFEL",title:"Een kijkje van dichtbij.",photos:[{src:"/images/fig-salad.webp",alt:"Salade met verse vijgen, sla, tomaten, croutons en plakjes ham",caption:"Verse vijgen & knapperige sla.",width:975,height:1300},{src:"/images/burrata-peach.webp",alt:"Burrata op rucola met gegrild fruit en pistachenoten",caption:"Burrata, fruit & kleur.",width:1200,height:800}]},
footer:{back:"Naar boven",line:"Met aandacht bereid. Met plezier gedeeld."}
},
en: {
pageTitle:"Pauline cooks | Grazing boxes, lunch & buffets in Arcen",meta:"Personal catering from Arcen. Grazing boxes, lunch, brunch and warm or cold buffets for private celebrations and company events. A tailored quote and a reply within 48 hours.",skip:"Skip to the food",navigation:"Main navigation",closeMenu:"Close menu",openMenu:"Open menu",close:"Close",
nav:{services:[["box","Grazing box"],["lunch","Lunch or brunch"],["cold","Warm & cold buffet"]],story:"Meet Pauline",contact:"Contact"},
hero:{eyebrow:"CATERING · ARCEN & SURROUNDINGS",line1:"Good food.",line2:"Great company.",intro:"From a generous grazing box to a table for everyone. Food prepared with care, for your kind of gathering.",cta:"Explore the food",secondary:"Tell me your plans",note:"With love, from Pauline",bottom:"FOR LITTLE CELEBRATIONS & BIG MOMENTS"},
offers:{eyebrow:"3 WAYS TO BRING PEOPLE TOGETHER",title1:"Your people.",title2:"Your table.",intro:"A baby shower at home, a birthday or lunch with the team. Choose what feels right; we’ll work out the details together.",details:"See what’s included",personal:"Every table is different.",flexible:"Your own idea, a favourite dish or a vegetarian preference? I’d love to hear it.",ask:"Talk through your wishes",cards:[
{id:"box",tag:"GRAZE & SHARE",title:"Grazing box",alt:"Cheese, bread, nuts and vegetables on a generous grazing board",description:"A generous box of cheeses, charcuterie, dips, bread and fresh extras. Delivered ready to put on the table.",expectation:"For drinks, birthdays and evenings with friends."},
{id:"lunch",tag:"SWEET & SAVOURY",title:"Lunch or brunch",alt:"Bread topped with smoked salmon, cream cheese, cucumber and herbs",description:"Filled rolls, fresh salads and something sweet. Or make it brunch with croissants, yoghurt and fruit.",expectation:"For baby showers, family gatherings and team lunches."},
{id:"cold",tag:"COLD, WARM OR BOTH",title:"A buffet your way",alt:"A buffet display of sandwiches and different savoury bites",description:"Colourful sharing dishes, warm favourites or a little of both. We’ll create one menu that works for your whole gathering.",expectation:"For celebrations at home and events at work."}]},
occasionsLabel:"Occasions",occasions:["Baby showers","Birthdays","Anniversaries","Team lunches","Company gatherings"],
menu:{eyebrow:"WHAT’S ON THE TABLE?",title1:"A little",title2:"food for thought.",intro:"A taste of the possibilities. Tell me what you like, and we’ll put together a menu that feels right.",choose:"Choose a menu type",instruction:"Choose an option below to explore its menu.",view:"View menu",current:"Menu open",tabs:[["box","Grazing box"],["lunch","Lunch & brunch"],["cold","Cold buffet"],["warm","Warm buffet"]],expect:"GOOD TO KNOW",cta:"Plan something like this",inspiration:"MENU INSPIRATION",footnote:"These are menu ideas. We’ll confirm the dishes, quantities and price together. Please mention allergies and dietary requirements in your enquiry."},
story:{eyebrow:"NEW IN ARCEN · EST. 2026",title1:"Hello,",title2:"I’m Pauline.",alt:"Pauline, the person behind Pauline cooks",caption:"The person behind your table",p1:"Growing up, getting together often started in the kitchen. My parents and grandmother cooked to bring the family together. That feeling stays with everything I make.",p2:"I grew up in Provence, I’m a mum of two, and I’m now starting my own catering business in Arcen. Pauline cooks is new. My love of cooking and sharing has been around much longer.",p3:"I listen to what you have in mind, prepare with care and give each gathering my full attention. Good food, thoughtful presentation and a welcoming feeling. That’s what I’m here for."},
process:{eyebrow:"FROM FIRST IDEA TO FIRST BITE",title:"Let’s keep it simple.",cta:"Let’s get started",steps:[{title:"Tell me your plans",body:"A date, roughly how many guests and your idea. Don’t have every detail yet? That’s absolutely fine."},{title:"A proposal for you",body:"I’ll reply within 48 hours. We’ll discuss the menu, possibilities and delivery, with a clear price before you decide."},{title:"Enjoy your company",body:"Once you approve, we confirm the arrangements. I look after the food so you have time for your guests."}]},
contact:{eyebrow:"A SMALL IDEA OR SOMETHING ALREADY PLANNED",title1:"Let’s make",title2:"something lovely.",intro:"Tell me what you have in mind. I’m happy to help you figure it out, even if you’re not sure what you’re looking for yet.",response:"A personal reply within 48 hours",deliveryTitle:"From Arcen to your gathering.",delivery:"I deliver personally in Arcen and the surrounding area. Enquiries from just across the German border are welcome too. Share your town or postcode; distance, delivery costs and any setup will be agreed in your proposal."},
serviceOptions:[["unsure","I’m not sure yet"],["box","Grazing box"],["lunch","Lunch or brunch"],["buffet","Cold or warm buffet"],["other","Another idea / a combination"]],
form:{heading:"What do you have in mind?",description:"Only your name and email are needed. Share any other details you already know.",name:"Name",email:"Email",service:"I’m interested in",date:"Date",dateOptional:"Date (if known)",guests:"Number of guests",guestsOptional:"Guests (approximately)",guestsPlaceholder:"For example, 20",occasion:"Occasion",occasionOptional:"Occasion (optional)",occasionPlaceholder:"For example, birthday or team lunch",city:"Town / postcode",cityOptional:"Town / postcode (optional)",cityPlaceholder:"For example, Arcen or Straelen",wishes:"Wishes",wishesOptional:"Tell me your wishes (optional)",wishesPlaceholder:"What are you planning? Favourite dishes, a budget or dietary requirements?",emailButton:"Continue by email",handoff:"Your email app or WhatsApp opens with your enquiry filled in. Review the message and send it there yourself.",copy:"Copy my enquiry",privacy:"Privacy",unknown:"Not yet decided",noWishes:"I’d love to discuss the possibilities.",greeting:"Hello Pauline,",intro:"I’d like to discuss catering for my gathering.",signoff:"Kind regards,",subject:"Catering enquiry — Pauline cooks",draftNotice:"Your message is ready to send. Finish sending it in your email app or WhatsApp. Nothing has been sent automatically.",copied:"Your enquiry has been copied. Paste it into an email to paulinecooks@gmail.com or into WhatsApp and send it there.",copyFailed:"Couldn’t copy your message. Use the email or WhatsApp button, or email paulinecooks@gmail.com directly."},
privacy:{intro:"Your enquiry, personally handled.",paragraphs:["Anything you enter here is shared only when you send the message yourself in your email app or WhatsApp. This page does not store your form details.","Pauline uses the information you send to answer your question and arrange any catering you book. To ask about your information, contact Pauline directly.","The website only remembers your language preference on this device. No advertising trackers have been added. Your email provider’s and WhatsApp’s terms also apply when you use those services."]},
gallery:{eyebrow:"ON THE TABLE",title:"A closer look.",photos:[{src:"/images/fig-salad.webp",alt:"Salad with fresh figs, lettuce, tomatoes, croutons and sliced ham",caption:"Fresh figs & crisp greens.",width:975,height:1300},{src:"/images/burrata-peach.webp",alt:"Burrata on rocket with grilled fruit and pistachios",caption:"Burrata, fruit & colour.",width:1200,height:800}]},
footer:{back:"Back to top",line:"Prepared with care. Shared with pleasure."}
}
};
export const menus = {
nl:[
{id:"box",script:"Openen. Delen. Genieten.",title:"Een borrel, zo op tafel.",description:"Een rijkgevulde box die je eenvoudig neerzet en deelt. De samenstelling stemmen we af op je gezelschap en het seizoen.",expect:"Bedoeld om te borrelen. Wil je er een volledige maaltijd van maken? Dan kijken we samen naar extra gerechten. Bezorging en prijs spreken we vooraf af.",groups:[{title:"DE BASIS",items:["Een selectie kazen","Charcuterie","Brood & crackers"]},{title:"DIPPEN & DELEN",items:["Twee dips, bijvoorbeeld hummus en roomkaas","Olijven & noten","Vers fruit & knapperige groenten"]},{title:"JOUW WENSEN",items:["Vegetarische invulling in overleg","Een grotere groep of extra hapjes? Vraag naar de mogelijkheden."]}]},
{id:"lunch",script:"Neem er even de tijd voor.",title:"Van teamlunch tot luie brunch.",description:"Hartige en zoete gerechten om samen van te genieten. Praktisch voor de vergadertafel, feestelijk voor een babyshower of zondag thuis.",expect:"Broodjes, salades en zoet stemmen we af op je groep. Je ontvangt een voorstel met de inhoud, aantallen en bezorging. Ook een vegetarische invulling is bespreekbaar.",groups:[{title:"LUNCH-IDEE",items:["Kleine belegde broodjes","Bijvoorbeeld zalm & roomkaas of tomaat & mozzarella","Frisse salade","Een stukje cake of brownie"]},{title:"BRUNCH-IDEE",items:["Gevulde croissants & kleine broodjes","Bijvoorbeeld zalm of rauwe ham","Yoghurt met granola","Vers fruit","Cake of bananenbrood"]}]},
{id:"cold",script:"Een tafel vol om te delen.",title:"Fris, royaal en kleurrijk.",description:"Salades, dips, brood en hartige gerechten op schalen. Kies je favorieten en we maken er een samenhangend buffet van.",expect:"Van bezorgde schalen tot een opgemaakte grazing table: vertel me hoe je het voor je ziet. Presentatie, eventuele opbouw en materialen worden apart afgesproken.",groups:[{title:"BROOD & DIPS",items:["Baguette of focaccia","Fetacrème met geroosterde tomaten","Hummus met granaatappel","Huisgemaakte tzatziki","Rode pesto of olijventapenade"]},{title:"SALADES & HARTIG",items:["Burrata met seizoensgroenten","Tomaat, mozzarella & basilicum","Couscoussalade met verse kruiden","Mediterrane pastasalade","Seizoensquiche","Gerookte zalm met citroen & dille","Carpaccio met Parmezaan & truffelmayonaise"]},{title:"ERBIJ",items:["Kazen & charcuterie","Vers seizoensfruit"]}]},
{id:"warm",script:"Schep gerust nog eens op.",title:"Warm eten, fijn gezelschap.",description:"Vertrouwde gerechten, royaal geserveerd. Combineer warme gerechten met frisse bijgerechten, of vul aan met iets van het koude buffet.",expect:"We stemmen het menu en de hoeveelheden samen af. Bezorgtijd, warmhouden, benodigde materialen en eventuele opbouw spreken we vooraf af voor jouw locatie.",groups:[{title:"HOOFDGERECHTEN",items:["Zalmfilet met citroen & kruiden","Kipsaté met pindasaus","Gehaktballetjes in tomatensaus","Beenham met honing-mosterdsaus","Paddenstoelenrisotto"]},{title:"BIJGERECHTEN",items:["Geroosterde aardappelen","Aardappelgratin","Geroosterde seizoensgroenten","Brood, dips of een frisse salade"]},{title:"IETS ZOETS",items:["Limburgse vlaai","Tiramisu","Appelcake","Brownies"]}]}
],
en:[
{id:"box",script:"Open. Share. Enjoy.",title:"Good company, meet good food.",description:"A generous box you can simply put on the table and share. We’ll choose a combination that suits your group and the season.",expect:"Designed for grazing alongside drinks. If you’d like a full meal, we can discuss adding dishes. Delivery and the price are agreed in advance.",groups:[{title:"THE FOUNDATION",items:["A selection of cheeses","Charcuterie","Bread & crackers"]},{title:"DIP & SHARE",items:["Two dips, such as hummus and cream cheese","Olives & nuts","Fresh fruit & crunchy vegetables"]},{title:"MAKE IT YOURS",items:["Vegetarian options by arrangement","A larger group or some extra bites? Ask about the possibilities."]}]},
{id:"lunch",script:"Take a little time together.",title:"From team lunch to slow brunch.",description:"Sweet and savoury food to enjoy together. Easy for a meeting, special enough for a baby shower or a Sunday at home.",expect:"We’ll tailor the rolls, salads and sweet treats to your group. Your proposal confirms the contents, quantities and delivery. Vegetarian options can be discussed too.",groups:[{title:"A LUNCH IDEA",items:["Small filled rolls","For example, salmon & cream cheese or tomato & mozzarella","Fresh salad","A slice of cake or a brownie"]},{title:"A BRUNCH IDEA",items:["Filled croissants & small sandwiches","For example, salmon or prosciutto","Yoghurt with granola","Fresh fruit","Cake or banana bread"]}]},
{id:"cold",script:"A table made for sharing.",title:"Fresh, generous and colourful.",description:"Salads, dips, bread and savoury dishes on sharing platters. Choose your favourites and we’ll turn them into a balanced buffet.",expect:"From delivered platters to a styled grazing table: tell me how you picture it. Presentation, any setup and serving equipment are agreed separately.",groups:[{title:"BREAD & DIPS",items:["Baguette or focaccia","Whipped feta with roasted tomatoes","Hummus with pomegranate","Homemade tzatziki","Red pesto or olive tapenade"]},{title:"SALADS & SAVOURY",items:["Burrata with seasonal vegetables","Tomato, mozzarella & basil","Couscous salad with fresh herbs","Mediterranean pasta salad","Seasonal quiche","Smoked salmon with lemon & dill","Carpaccio with Parmesan & truffle mayonnaise"]},{title:"A LITTLE EXTRA",items:["Cheese & charcuterie","Fresh seasonal fruit"]}]},
{id:"warm",script:"There’s always room for seconds.",title:"Warm food, happy company.",description:"Familiar favourites, generously served. Combine warm dishes with fresh sides, or add something from the cold buffet.",expect:"We’ll agree on the menu and quantities together. Delivery timing, keeping food warm, serving equipment and any setup are discussed for your location in advance.",groups:[{title:"MAIN DISHES",items:["Salmon fillet with lemon & herbs","Chicken satay with peanut sauce","Meatballs in tomato sauce","Ham with honey-mustard sauce","Mushroom risotto"]},{title:"ON THE SIDE",items:["Roasted potatoes","Potato gratin","Roasted seasonal vegetables","Bread, dips or a fresh salad"]},{title:"SOMETHING SWEET",items:["Limburgse vlaai","Tiramisu","Apple cake","Brownies"]}]}
]
};
